# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        domain: globalusercenter.fun
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.52.171:3306/okai_db?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wzwcx1029!
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 120.26.52.171
    port: 6379
    timeout: 86400
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
#mybatis-plus:
#  configuration:
#    # 生产环境关闭日志
#    log-impl: ''

